- src/app/modules/consultations/consultation-profile/consultation-public-responses/consultation-public-responses.component.ts
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.html
- src/app/shared/components/auth-modal/auth-modal.component.ts
* fix: Minor check with questions length
* fix: Added consultation id in auth modal and isverified status in response
> Civ 443 (#197)

- src/app/modules/auth-private/forgot-password/forgot-password.component.html
- src/app/modules/auth-private/forgot-password/forgot-password.graphql.ts
- src/app/modules/auth-private/sign-up/sign-up.component.html
- src/app/modules/auth/forgot-password/forgot-password.component.html
- src/app/modules/auth/forgot-password/forgot-password.graphql.ts
- src/app/modules/auth/sign-up/sign-up.component.html
- src/app/shared/components/auth-modal/auth-modal.component.html
* feat(api!): password length to 8 char
* fix: dropped accessToken from authForgotPassword API
* fix: feedback changes
* feat: added error msgs
* chore : error msg changed for password
> feat: Civ 570 (#264)

- src/app/modules/auth-private/sign-up/sign-up.component.html
- src/app/modules/auth-private/sign-up/sign-up.component.scss
- src/app/modules/auth/sign-up/sign-up.component.html
- src/app/modules/auth/sign-up/sign-up.component.scss
- src/app/shared/components/auth-modal/auth-modal.component.html
- src/app/shared/components/auth-modal/auth-modal.component.scss
> chore(CIV-570p): label and ui

- src/app/graphql/queries.graphql.ts
- src/app/modules/consultations/consultation-profile/consultation-public-responses/consultation-public-responses.component.ts
- src/app/modules/consultations/response/response.component.html
- src/app/shared/components/response-answers/response-answers.component.html
> feat(CIV-506):  added response for current user

- src/app/modules/consultations/consultation-profile/profile-card/profile-card.component.html
[CIV-409](https://commutatus.atlassian.net/browse/CIV-409)
> fix: Hide 'TOTAL PUBLIC RESPONSES' for policy reviews only

- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.ts
- src/app/modules/consultations/consultation-profile/consultation-response-text/consultation-response-text.component.ts
[CIV-604](https://commutatus.atlassian.net/browse/CIV-604)
> hotfix: Add responseStatus as workaround for the pending JP Morgan changes

- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.ts
- src/app/modules/consultations/consultation-profile/consultation-response-text/consultation-response-text.component.ts
https://github.com/civis-vote/civis-frontend/pull/302
> fix: Public response not working

- package.json
- server.js
Implemented CSP header.
According to [this](https://awesome.commutatus.com/resources/mozilla-score) guide, response header has been populated with CSP using the `helmet-csp` package in `server.js`.
Further external resources has been added.
> Chore(CIV-569): added CSP header

- package.json
- server.js
Reverts civis-vote/civis-frontend#319
> Revert "Chore(CIV-569): added CSP header"

- src/index.html
Reverts civis-vote/civis-frontend#320
Added in customHttp.yml in AWS console.
> Revert "Chore(CIV-569): added meta tag for CSP in index.html"

- customHttp.yml
- src/app/modules/consultations/consultation-profile/thank-you-modal/thank-you-modal.component.ts
Added meta pixel Lead event to track consultation response submission for a particular consultation.
Civis team wants to track conversions for this particular consultation.
Added meta pixel Lead event which will be fired when thank you modal loads on the page.
Tested to verify that the Lead event is getting fired when thank you modal loads.
##Anything Else
I tried doing this through GTM but  the event is not getting triggered and the client wants this asap, So I have added this through the codebase.
> chore(PRO-378): Added meta pixel Lead event to track consultation response submission for a particular consultation

- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.ts
- Uncomment code for showing auth modal
> fix: Auth prompt when submitting response

- src/app/modules/consultations/consultation-profile/consultation-profile.graphql.ts
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.ts
- Added condition to skip the checking of If user is not authenticated for consultation 404 and 707
> fix: Skip login for specific consultation.

- src/app/modules/consultations/consultation-profile/profile-card/profile-card.component.html
> fix: resolved build error.

- src/app/modules/auth-private/login/login.component.html
- src/app/modules/auth/login/login.component.html
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.html
- src/app/modules/consultations/consultation-profile/consultation-response-text/consultation-response-text.component.html
- src/app/modules/consultations/consultation-profile/profile-card/profile-card.component.html
- src/app/modules/consultations/consultation-profile/satisfaction-rating-selection/satisfaction-rating-selection.component.html
- src/app/modules/glossary/glossary.component.html
- src/app/modules/landing/landing.component.html
- src/app/shared/components/footer/footer.component.html
- src/app/shared/models/constants/translation.json
fix: Updated missing translation strings
> fix: Updated missing translation strings

- src/app/app.component.ts
- src/app/modules/consultations/consultation-profile/consultation-profile.graphql.ts
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.html
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.ts
- src/app/modules/consultations/consultation-profile/profile-card/profile-card.component.html
- src/app/modules/consultations/consultation-profile/profile-card/profile-card.component.ts
- src/app/modules/consultations/consultation-profile/read-respond/read-respond.component.html
- src/app/modules/consultations/consultation-profile/read-respond/read-respond.component.scss
- src/app/modules/consultations/consultation-profile/read-respond/read-respond.component.ts
- src/app/modules/consultations/consultations-summary/consultations-summary.graphql.ts
- src/app/shared/components/footer/footer.component.ts
- src/app/shared/functions/modular.functions.ts
- src/app/shared/services/translation.service.ts
feat: 
- Implemented a language dropdown in the summary section 
- And updated API, translations to support Hindi and Odia for dynamic content, including titles, ministries, summaries, questions, and sub-questions.
> feat: Implemented a language dropdown in the summary section

- sortTranslation.js
- src/app/app.component.ts
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.html
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.ts
- src/app/modules/consultations/consultation-profile/profile-card/profile-card.component.ts
- src/app/modules/consultations/consultation-profile/read-respond/read-respond.component.ts
- src/app/shared/components/footer/footer.component.html
- src/app/shared/components/footer/footer.component.ts
- src/app/shared/functions/modular.functions.ts
- src/app/shared/models/constants/translation-utils.js
- src/app/shared/models/constants/translation.json
- src/app/shared/services/translation.service.ts
feat: Add Static Text Translation to Odia and Update Translation Logic for Staging
Updated translation.json to include Odia (od), Hindi (hi), and English (en) translations.
Added translation-utils.js script to handle static string translations using the Sarvam API.
Implemented translations for tooltips and the getDifferenceInDays function.
> feat: Translation of Static Text to Odia to staging

- src/app/modules/consultations/consultation-profile/read-respond/read-respond.component.ts
> fix: updated odia id

- src/app/shared/components/consultation-card/consultation-card.component.html
- src/app/shared/components/consultation-card/consultation-card.component.ts
refactor: getRemainingDays function in consultation page.
> refactor: getRemainigDays function in consultation page.

- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.ts
- src/app/modules/consultations/consultation-profile/consultation-response-text/consultation-response-text.component.ts
Fix: Reduced multiple calling of API while submitting consultations.
> fix: To stop calling the API multiple times

- src/app/modules/consultations/consultation-profile/profile-card/profile-card.component.ts
- src/app/shared/components/consultation-card/consultation-card.component.ts
Refactored : getRemainingDaysText
> Refactored: RemainingDaysText

- src/app/shared/components/footer/footer.component.html
refactor: Added the CIN number in the footer.
> refactor: Added the CIN number in the footer.

- src/app/modules/landing/landing.component.html
main PR: https://github.com/civis-vote/civis-frontend/pull/548
> Refactor: Updated the g-forms url

- src/app/modules/landing/landing.component.html
main PR: https://github.com/civis-vote/civis-frontend/pull/548
> Refactor: Updated the section text.

- src/app/modules/consultations/consultation-profile/consultation-profile.graphql.ts
- src/app/modules/navbar/navbar.component.html
- src/app/modules/navbar/navbar.component.scss
- src/app/modules/navbar/navbar.component.ts
https://github.com/civis-vote/civis-frontend/pull/566
> feat: Override Civis logo

- src/app/modules/navbar/navbar.component.html
Updated Donate link to open in new tab!
> chore: Updated Donate link to open in new tab

- src/app/modules/consultations/consultation-profile/consultation-public-responses/consultation-public-responses.component.html
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.ts
- Removed the tag from the content.
- Removed the console logs.
> fix: UI improvements

- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.html
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.ts
> [staging] fix: Updated consultation response validations

- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.html
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.ts
- Added validation to prevent submission without selecting a Satisfaction Rating
> fix: Updated consultation response validations

- src/app/graphql/queries.graphql.ts
- src/app/modules/consultations/consultation-list/consultation-list.graphql.ts
- src/app/modules/consultations/consultation-profile/consultation-profile.graphql.ts
- src/app/modules/consultations/consultations-summary/consultations-summary.graphql.ts
- src/app/modules/consultations/response/response.graphql.ts
- src/app/modules/landing/landing.graphql.ts
- src/app/modules/leader-board/leader-board.graphql.ts
- src/app/shared/user-profile-modal/user-profile.graphql.ts
Main PR: https://github.com/civis-vote/civis-frontend/pull/625
> [staging] fix: replaced X with x in resolution

- src/app/graphql/queries.graphql.ts
- src/app/modules/consultations/consultation-list/consultation-list.graphql.ts
- src/app/modules/consultations/consultation-profile/consultation-profile.graphql.ts
- src/app/modules/consultations/consultations-summary/consultations-summary.graphql.ts
- src/app/modules/consultations/response/response.graphql.ts
- src/app/modules/landing/landing.graphql.ts
- src/app/modules/leader-board/leader-board.graphql.ts
- src/app/shared/user-profile-modal/user-profile.graphql.ts
Main PR: https://github.com/civis-vote/civis-frontend/pull/625
> [staging] fix: fixed caching issue

- src/app/modules/consultations/consultation-profile/consultation-profile.component.html
- src/app/modules/consultations/consultation-profile/consultation-profile.component.scss
- src/app/modules/consultations/consultation-profile/consultation-profile.component.ts
- src/app/modules/consultations/consultation-profile/profile-card/profile-card.component.html
- src/app/modules/consultations/consultation-profile/profile-card/profile-card.component.ts
- src/app/modules/consultations/consultation-profile/read-respond/read-respond.component.html
> [staging] feat: Added loading state and spinner for consultation profile page.

- src/app/modules/consultations/consultation-profile/consultation-profile.component.html
- src/app/modules/consultations/consultation-profile/consultation-profile.component.scss
- src/app/modules/consultations/consultation-profile/consultation-profile.component.ts
- src/app/modules/consultations/consultation-profile/consultation-profile.graphql.ts
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.ts
- src/app/modules/consultations/consultation-profile/profile-card/profile-card.component.html
- src/app/modules/consultations/consultation-profile/profile-card/profile-card.component.ts
- src/app/modules/consultations/consultation-profile/read-respond/read-respond.component.html
- Added HasUserFilledResponseInCurrentResponseRound field and removed the `anonymousResponses` checking logic
> refactor: Added HasUserFilledResponseInCurrentResponseRound field 

- src/app/modules/consultations/consultation-profile/consultation-profile.graphql.ts
- src/app/modules/consultations/consultation-profile/consultation-questionnaire/consultation-questionnaire.component.html
- src/app/modules/consultations/consultation-profile/read-respond/read-respond.component.html
- src/app/modules/consultations/consultation-profile/satisfaction-rating-selection/satisfaction-rating-selection.component.html
- src/app/modules/consultations/consultations-summary/consultations-summary.component.html
- Use the showSatisfactionRating flag to render satisfaction rating UI elements conditionally.
> feat: Added showSatisfactionRating field

- src/app/modules/consultations/consultation-profile/consultation-profile.component.html
- src/app/modules/consultations/consultation-profile/consultation-profile.component.scss
- Removed private consultation default background image.
> remove: Private consultation background styling and class binding
